/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.AgendamentoDAO;
import dao.ParceiroDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.Agendamento;
import modelo.Caixa;
import modelo.Parceiro;

/**
 *
 * @author akiot
 */
public class AgendamentoVisao extends JDialog {
    
    private final ParceiroDAO parceiroDAO;
    private List<Parceiro> parceiros;
    private final AgendamentoDAO agendamentoDAO;
    private List<Agendamento> agendamentos;
    private Caixa caixaAberto;
    private Agendamento agendamentoNovo;

    /**
     * Creates new form AgendamentoVisao
     */
    public AgendamentoVisao() {
        initComponents();
        parceiroDAO = new ParceiroDAO();
        agendamentoDAO = new AgendamentoDAO();
        atualizaParceiros(parceiroDAO.findAll());
    }
    
    AgendamentoVisao(Caixa caixaAberto, Date date) {
        initComponents();
        jDateChooserDataAgendamento.setDate(date);
        parceiroDAO = new ParceiroDAO();
        agendamentoDAO = new AgendamentoDAO();
        atualizaParceiros(parceiroDAO.findAll());
        this.caixaAberto = caixaAberto;
        
    }
    
    AgendamentoVisao(Caixa caixaAberto, Agendamento agendamento) {
        initComponents();
        jDateChooserDataAgendamento.setDate(agendamento.getDataagendamento());
        jComboBoxHorario.setSelectedItem(""+agendamento.getDataagendamento().getHours());
        jComboBoxHorario.setEnabled(false);
        
        parceiroDAO = new ParceiroDAO();
        agendamentoDAO = new AgendamentoDAO();
        atualizaParceiros(parceiroDAO.findAll());
        jDateChooserDataAgendamento.setEnabled(false);
        
        this.caixaAberto = caixaAberto;
        agendamentoNovo = agendamento;
        
    }
    
    private void atualizaParceiros(List<Parceiro> parceiros) {
        String str = null;
        
        for (int i = 0; i < parceiros.size(); i++) {
            
            str = (String) parceiros.get(i).getNome();
            jComboBoxParceiro.addItem(str);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jDateChooserDataAgendamento = new com.toedter.calendar.JDateChooser();
        jComboBoxHorario = new javax.swing.JComboBox<>();
        jButtonAgendar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObserv = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTipoVeiculo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonSemCadastro = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jRadioButtonSemParceiro = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBoxParceiro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento");

        jTextField3.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel4.setText("Endereço:");

        jTextFieldEndereco.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N

        jDateChooserDataAgendamento.setForeground(new java.awt.Color(204, 0, 51));
        jDateChooserDataAgendamento.setDateFormatString("dd/MM/yy");
        jDateChooserDataAgendamento.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jDateChooserDataAgendamento.setOpaque(false);

        jComboBoxHorario.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jComboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));

        jButtonAgendar.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jButtonAgendar.setText("Agendar");
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel5.setText("Horário:");

        jLabel6.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel6.setText("Observações:");

        jTextAreaObserv.setColumns(20);
        jTextAreaObserv.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObserv);

        jLabel7.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel7.setText("Tipo de Veiculo:");

        jComboBoxTipoVeiculo.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jComboBoxTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Carro", "Moto", "Caminhão", "Ônibus", "Reboque", "Outro" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel8.setText("DATA:");

        jRadioButtonSemCadastro.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jRadioButtonSemCadastro.setSelected(true);
        jRadioButtonSemCadastro.setText("Sem cadastro");

        jRadioButton2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jRadioButton2.setText("Cliente:");

        jButton4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        jButton4.setText("OK");

        jRadioButtonSemParceiro.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jRadioButtonSemParceiro.setSelected(true);
        jRadioButtonSemParceiro.setText("Sem parceiro");

        jRadioButton4.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jRadioButton4.setText("Parceiro:");

        jComboBoxParceiro.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jComboBoxParceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jLabel3.setText("Agendamento");

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel2.setText("Telefone:");

        jTextFieldTelefone.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonSemCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(jButtonAgendar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTipoVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDataAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonSemParceiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxParceiro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEndereco)
                                .addGap(11, 11, 11)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel8))
                    .addComponent(jDateChooserDataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSemCadastro)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSemParceiro)
                    .addComponent(jRadioButton4)
                    .addComponent(jComboBoxParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgendar)
                            .addComponent(jButtonCancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDateChooserDataAgendamento, jLabel3, jLabel8});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxHorario, jComboBoxParceiro, jComboBoxTipoVeiculo, jTextField3, jTextFieldEndereco, jTextFieldTelefone});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        Agendamento novoagendamento = new Agendamento();
        if (jRadioButtonSemParceiro.isSelected()) {
            novoagendamento.setParceiro(null);
        } else {
            novoagendamento.setParceiro(parceiroDAO.findByNome(jComboBoxParceiro.getSelectedItem().toString()).get(0));
        }
        if (jRadioButtonSemCadastro.isSelected()) {
            novoagendamento.setCliente(null);
        } // Criar novo cliente e fazer a busca com DAO de acordo com o valor do jtext.
        else {
            
        }
        novoagendamento.setDataagendamento(jDateChooserDataAgendamento.getDate());
        
        if (jComboBoxTipoVeiculo.getSelectedItem() != "Selecione") {
            novoagendamento.setTipoveiculo(jComboBoxTipoVeiculo.getSelectedItem().toString());
        } else {
            
        }

// Verifica se foi selecionado algum horario, caso sim, altera somente o horário no date.
        if (jComboBoxHorario.getSelectedItem() != "Selecione") {
            novoagendamento.getDataagendamento().setHours(Integer.parseInt("" + jComboBoxHorario.getSelectedItem()));
        }
        
        novoagendamento.setEndereco(jTextFieldEndereco.getText());
        novoagendamento.setObservacao(jTextAreaObserv.getText());
        novoagendamento.setCaixa(caixaAberto);
        novoagendamento.setTelefone(jTextFieldTelefone.getText());

// Se não receber o código por parametro, ou seja, não existe agendamento para o dia.
        if (agendamentoNovo == null) {
            
            switch (jComboBoxHorario.getSelectedItem().toString()) {
                case "8":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "9":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "10":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "11":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "12":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "13":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "14":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "15":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "16":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 17);
                    break;
                case "17":
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 8);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 9);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 10);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 11);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 12);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 13);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 14);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 15);
                    agendaVazia(jDateChooserDataAgendamento.getDate(), 16);
                    break;
                
            }
            
        } // Existe agendamento marcado no dia.
        else {
            novoagendamento.setCodigo(agendamentoNovo.getCodigo());
        }
        agendamentoDAO.merge(novoagendamento);
        JOptionPane.showMessageDialog(null, "O agendamento foi salvo!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_jButtonAgendarActionPerformed
    
    private void agendaVazia(Date date, int horario) {
        date.setHours(horario);
        date.setMinutes(0);
        
        Agendamento novoagendamento = new Agendamento();
        novoagendamento.setParceiro(null);
        novoagendamento.setCliente(null);
        novoagendamento.setDataagendamento(date);
        novoagendamento.setEndereco(null);
        novoagendamento.setCaixa(null);
        novoagendamento.setObservacao("");
        novoagendamento.setTipoveiculo(null);
        agendamentoDAO.merge(novoagendamento);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendamentoVisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JComboBox<String> jComboBoxParceiro;
    private javax.swing.JComboBox<String> jComboBoxTipoVeiculo;
    private com.toedter.calendar.JDateChooser jDateChooserDataAgendamento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButtonSemCadastro;
    private javax.swing.JRadioButton jRadioButtonSemParceiro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObserv;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
