/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ClienteDAO;
import dao.ParceiroDAO;
import dao.VeiculoDAO;
import dao.VistoriaDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.Caixa;
import modelo.Cliente;
import modelo.Pagamento;
import modelo.Parceiro;
import modelo.Veiculo;
import modelo.Vistoria;

/**
 *
 * @author akiot
 */
public class VistoriaVisao extends JDialog {

    private final VistoriaDAO vistoriaDAO;
    private List<Vistoria> vistorias;

    private final ClienteDAO clienteDAO;
    private List<Cliente> clientes;

    private final VeiculoDAO veiculoDAO;
    private List<Veiculo> veiculos;

    private final ParceiroDAO parceiroDAO;
    private List<Parceiro> parceiros;
    Vistoria editarVistoria = new Vistoria();
    Caixa caixaAberto = new Caixa();

    /**
     * Creates new form CadastroCliente
     */
    public VistoriaVisao() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/vistotec-logo.png")).getImage());
        vistoriaDAO = new VistoriaDAO();
        veiculoDAO = new VeiculoDAO();
        clienteDAO = new ClienteDAO();
        parceiroDAO = new ParceiroDAO();
        jComboBoxOpPesquisa.setEnabled(false);
        PainelComAbas.setEnabledAt(1, false);
        atualizaParceiros(parceiroDAO.findAll());
        atualizaTabela(vistoriaDAO.findAllOrder());
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");

    }

    VistoriaVisao(Caixa caixa) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/vistotec-logo.png")).getImage());
        vistoriaDAO = new VistoriaDAO();
        veiculoDAO = new VeiculoDAO();
        clienteDAO = new ClienteDAO();
        parceiroDAO = new ParceiroDAO();
        caixaAberto = caixa;
        PainelComAbas.setEnabledAt(1, false);
        atualizaParceiros(parceiroDAO.findAll());
        atualizaTabela(vistoriaDAO.findAllOrder());
        jComboBoxOpPesquisa.setEnabled(false);
    }

    VistoriaVisao(boolean b, Caixa caixa) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/vistotec-logo.png")).getImage());
        vistoriaDAO = new VistoriaDAO();
        veiculoDAO = new VeiculoDAO();
        clienteDAO = new ClienteDAO();
        parceiroDAO = new ParceiroDAO();
        caixaAberto = caixa;
        PainelComAbas.setEnabledAt(0, false);
        PainelComAbas.setEnabledAt(1, true);
        PainelComAbas.setSelectedIndex(1);
        jComboBoxOpPesquisa.setEnabled(false);
        atualizaParceiros(parceiroDAO.findAll());
        atualizaTabela(vistoriaDAO.findAllOrder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelComAbas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCampoPesquisa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jComboBoxOpPesquisa = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jRadioButtonPlaca = new javax.swing.JRadioButton();
        jButtonPago = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtModeloVeiculo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtMarcaVeiculo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldUltimaVistoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TxtCorVeiculo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldUltimaKm = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TxtNomeCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtTelefoneCliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxParceiro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldKilometragem = new javax.swing.JTextField();
        jButtonAdicionarPDF = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLaudo = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jRadioButtonAprovado = new javax.swing.JRadioButton();
        jRadioButtonReprovado = new javax.swing.JRadioButton();
        txtPDF = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabelMotivo = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VistoTEC - Vistorias");

        PainelComAbas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldCampoPesquisa.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldCampoPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCampoPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCampoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoPesquisaActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icones_pequenos/search_left [#1504].png"))); // NOI18N
        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Motivo", "Data", "Hora", "Situação", "Valor Cobrado", "Parceiro", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(5).setResizable(false);
            tabela.getColumnModel().getColumn(7).setResizable(false);
        }

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/deletar_icone.png"))); // NOI18N
        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxOpPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxOpPesquisa.setForeground(new java.awt.Color(0, 102, 153));
        jComboBoxOpPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa", "Nome", "Parceiro" }));
        jComboBoxOpPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpPesquisaActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 102, 153));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vistoria_icone.png"))); // NOI18N
        jButton8.setText("Novo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 102, 153));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar_icone.png"))); // NOI18N
        jButton9.setText("Editar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jRadioButtonPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPlacaActionPerformed(evt);
            }
        });

        jButtonPago.setBackground(new java.awt.Color(0, 102, 153));
        jButtonPago.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/mudar_icone.png"))); // NOI18N
        jButtonPago.setText("Mudar situação");
        jButtonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagoActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/close_icone.png"))); // NOI18N
        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pdf_icone.png"))); // NOI18N
        jButton5.setText("Ver PDF");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldCampoPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(142, 142, 142)
                        .addComponent(jButtonPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxOpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jButtonPago)
                        .addComponent(jButton2)
                        .addComponent(jButton7)
                        .addComponent(jButton5)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton3, jComboBoxOpPesquisa, jTextFieldCampoPesquisa});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton5, jButton7, jButton8, jButton9, jButtonPago});

        PainelComAbas.addTab("Vistorias", new javax.swing.ImageIcon(getClass().getResource("/icones/icones_pretos/carro.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Veiculo"));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel2.setText("Modelo");

        TxtModeloVeiculo.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel12.setText("Marca");

        TxtMarcaVeiculo.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel17.setText("Ultima Vistoria");

        jTextFieldUltimaVistoria.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel1.setText("Placa do Veiculo");

        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacaFocusGained(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TxtCorVeiculo.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel13.setText("Cor");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel18.setText("Ultima KIlometragem");

        jTextFieldUltimaKm.setEditable(false);

        jButton11.setBackground(new java.awt.Color(0, 102, 153));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icones_pequenos/search_left [#1504].png"))); // NOI18N
        jButton11.setText("Verificar Vistorias");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCorVeiculo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMarcaVeiculo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtModeloVeiculo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton11))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUltimaKm, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUltimaVistoria))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUltimaVistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMarcaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldUltimaKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCorVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton11))
                .addGap(10, 10, 10))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TxtCorVeiculo, TxtMarcaVeiculo, TxtModeloVeiculo, jButton1, jTextFieldUltimaKm, jTextFieldUltimaVistoria, txtPlaca});

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel14.setText("Nome do Cliente");

        TxtNomeCliente.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        TxtTelefoneCliente.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel16.setText("Telefone");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel5.setText("Cpf do Cliente");

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTelefoneCliente)
                                    .addComponent(TxtNomeCliente))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel15)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TxtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TxtNomeCliente, TxtTelefoneCliente, jButton4, txtCpf});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Vistoria"));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel9.setText("Parceiro");

        jComboBoxParceiro.setForeground(new java.awt.Color(0, 102, 153));
        jComboBoxParceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel11.setText("Kilometragem");

        jTextFieldKilometragem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldKilometragemKeyTyped(evt);
            }
        });

        jButtonAdicionarPDF.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAdicionarPDF.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButtonAdicionarPDF.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pdf_icone.png"))); // NOI18N
        jButtonAdicionarPDF.setText("Adicionar PDF");
        jButtonAdicionarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPDFActionPerformed(evt);
            }
        });

        jTextAreaLaudo.setColumns(20);
        jTextAreaLaudo.setRows(5);
        jTextAreaLaudo.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));
        jScrollPane3.setViewportView(jTextAreaLaudo);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jRadioButtonAprovado.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAprovado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonAprovado.setForeground(new java.awt.Color(51, 204, 0));
        jRadioButtonAprovado.setText("Aprovado");
        jRadioButtonAprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAprovadoActionPerformed(evt);
            }
        });

        jRadioButtonReprovado.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonReprovado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonReprovado.setForeground(new java.awt.Color(204, 0, 51));
        jRadioButtonReprovado.setText("Reprovado");
        jRadioButtonReprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReprovadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jRadioButtonAprovado)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonReprovado)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAprovado)
                    .addComponent(jRadioButtonReprovado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonAdicionarPDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxParceiro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldKilometragem)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxParceiro, jTextFieldKilometragem, txtPDF});

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivo da Vistoria"));

        jLabelMotivo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelMotivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotivo.setText("Transferência");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jButtonSalvar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar_icone.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar_icone.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Nova Vistoria");

        jTextFieldID.setEnabled(false);

        jLabel10.setText("ID");

        jButtonCancelar.setBackground(new java.awt.Color(204, 0, 51));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/close_icone.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonLimpar, jButtonSalvar});

        PainelComAbas.addTab("Formulário", new javax.swing.ImageIcon(getClass().getResource("/icones/icones_pretos/formulario.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelComAbas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelComAbas)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Vistoria v = new Vistoria();
        // Verifica se o campo PLACA está preenchido
        if (!"".equals(txtPlaca.getText())) {

            // Verifica se a busca pelo veiculo teve sucesso
            if (!"".equals(TxtModeloVeiculo.getText())) {
                Veiculo veiculo = veiculoDAO.findByPlaca(txtPlaca.getText()).get(0);
                v.setVeiculo(veiculo);

                // Verifica se o campo CPF está preenchido
                if (!"".equals(txtCpf.getText())) {

                    // Verifica se a busca pelo cliente teve sucesso
                    if (!"".equals(TxtNomeCliente.getText())) {
                        Cliente cliente = clienteDAO.findByCpf(txtCpf.getText()).get(0);
                        v.setCliente(cliente);

                        // Verifica se tem conteudo, pra saber se é uma alteração ou não
                        if ("".equals(jTextFieldID.getText())) {
                            // Salva apenas a data
                            v.setDatahora(new Date());

                        } else {
                            // Usa os valores salvos quando aperta o botão editar
                            v.setDatahora(editarVistoria.getDatahora());

                        }

                        // Verifica qual opção escolhida na jComboBox
                        if (jComboBoxParceiro.getSelectedItem() != "Nenhum") {
                            Parceiro parceiro = parceiroDAO.findByNome((String) jComboBoxParceiro.getSelectedItem()).get(0);
                            v.setParceiro(parceiro);
                        } else {
                            // Caso nenhuma esteja escolhida, ele coloca o valor null
                            v.setParceiro(null);
                        }

                        v.setCaixa(caixaAberto);

                        // Pega o ID e faz o merge , caso não tenha ele cria um novo registro
                        if (!"".equals(jTextFieldID.getText())) {
                            v.setId(Long.parseLong(jTextFieldID.getText()));
                        }

                        // Se o endereço do PDF estiver preenchido.
                        if (!txtPDF.getText().isEmpty()) {
                            v.setLocalpdf(txtPDF.getText());
                        }

                        if (jRadioButtonAprovado.isSelected()) {
                            v.setResultado('a');
                        }
                        if (jRadioButtonReprovado.isSelected()) {
                            v.setResultado('r');
                        }

                        v.setKilometragem(Long.parseLong(jTextFieldKilometragem.getText()));

                        v.setMotivo(jLabelMotivo.getText());

                        if ("".equals(jTextFieldID.getText())) {
                            if (!vistoriaDAO.findByPlaca(txtPlaca.getText()).isEmpty()) {
                                if (Integer.valueOf(jTextFieldUltimaKm.getText()) > Integer.valueOf(jTextFieldKilometragem.getText())) {

                                    int op = JOptionPane.showConfirmDialog(null, "Atenção! Veiculo com kilometragem inferior do laudo anterior, deseja continuar?");

                                    if (op == 0) {
                                        vistoriaDAO.merge(v);

                                        JOptionPane.showMessageDialog(null, "Dados foram gravados.", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                                        if (!jLabelMotivo.equals("Retorno")) {
                                            //Abre opção de pagamento.
                                            int opi = JOptionPane.showConfirmDialog(null, "Deseja registrar o pagamento?");

                                            // Se a opção for SIM.
                                            if (opi == 0) {
                                                PagamentoVistoria frame = new PagamentoVistoria(vistoriaDAO.findByPlaca(txtPlaca.getText()).get(0));
                                                frame.setModal(true);
                                                frame.setVisible(true);
                                            }
                                        }

                                    } else {
                                        jTextFieldKilometragem.requestFocusInWindow();
                                    }
                                } else {

                                    vistoriaDAO.merge(v);
                                    JOptionPane.showMessageDialog(null, "Dados foram gravados.", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                                    //Abre opção de pagamento.
                                    int op = JOptionPane.showConfirmDialog(null, "Deseja registrar o pagamento?");

                                    // Se a opção for SIM.
                                    if (op == 0) {
                                        PagamentoVistoria frame = new PagamentoVistoria(vistoriaDAO.findByPlaca(txtPlaca.getText()).get(0));
                                        frame.setModal(true);
                                        frame.setVisible(true);
                                    } else {

                                    }
                                }

                            } else {

                                vistoriaDAO.merge(v);
                                JOptionPane.showMessageDialog(null, "Dados foram gravados.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                                //Abre opção de pagamento.
                                int op = JOptionPane.showConfirmDialog(null, "Deseja registrar o pagamento?");

                                // Se a opção for SIM.
                                if (op == 0) {
                                    PagamentoVistoria frame = new PagamentoVistoria(vistoriaDAO.findByPlaca(txtPlaca.getText()).get(0));
                                    frame.setModal(true);
                                    frame.setVisible(true);
                                } else {

                                }
                            }
                        } else {
                            vistoriaDAO.merge(v);
                            JOptionPane.showMessageDialog(null, "Os dados foram editados.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        }

                        // Verifica as Km
                        atualizaTabela(vistoriaDAO.findAll());

                        limparCampos();
                        PainelComAbas.setEnabledAt(0, true);
                        PainelComAbas.setEnabledAt(1, false);
                        PainelComAbas.setSelectedIndex(0);

                    } else {
                        JOptionPane.showMessageDialog(null, "Cliente não verificado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        txtCpf.requestFocusInWindow();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Favor inserir o cpf.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    txtCpf.requestFocusInWindow();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Veiculo não verificado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtPlaca.requestFocusInWindow();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor inserir a placa.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            txtPlaca.requestFocusInWindow();

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// Verifica se o campo cpf está vazio
        if (!"".equals(txtCpf.getText())) {
            if (txtCpf.getText().length() == 14) {
                // Verifica se está vazia, o que significa que não teve retorno no DAO.
                if (!clienteDAO.findByCpf(txtCpf.getText()).isEmpty()) {

                    Cliente cliente = clienteDAO.findByCpf(txtCpf.getText()).get(0);
                    TxtNomeCliente.setText(cliente.getNome());
                    TxtTelefoneCliente.setText(cliente.getTelefone());
                } else {

                    int op = JOptionPane.showConfirmDialog(null, "Cliente não encontrado, deseja cadastrar?");

                    if (op == 0) {
                        ClienteVisao frame = new ClienteVisao(txtCpf.getText());

                        frame.setModal(true);
                        frame.setVisible(true);

                        jButton4.doClick();
                    } else {
                        TxtNomeCliente.setText("");
                        txtCpf.requestFocus();
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor digitar os 11 digitos do cpf");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor digitar no campo cpf");
            txtCpf.requestFocusInWindow();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Verifica se foi digitado algo no campo placa
        if (!"".equals(txtPlaca.getText())) {
            txtPlaca.setText(txtPlaca.getText().toUpperCase());

            //Permite somente 7 digitos
            if (txtPlaca.getText().length() == 7) {
                // Verifica se está vazia, o que significa que não teve retorno no DAO.
                if (!veiculoDAO.findByPlaca(txtPlaca.getText()).isEmpty()) {

                    Veiculo veiculo = veiculoDAO.findByPlaca(txtPlaca.getText()).get(0);
                    TxtModeloVeiculo.setText(veiculo.getModelo());
                    TxtMarcaVeiculo.setText(veiculo.getMarca());
                    TxtCorVeiculo.setText(veiculo.getCor());

                    // Verifica ultima vistoria e pega os dados
                    if (!vistoriaDAO.findByPlaca(txtPlaca.getText()).isEmpty()) {
                        DateFormat dateDia = new SimpleDateFormat("dd/MM/yyyy");
                        jTextFieldUltimaVistoria.setText("" + dateDia.format(vistoriaDAO.findByPlaca(txtPlaca.getText()).get(0).getDatahora()));

                        jTextFieldUltimaKm.setText("" + vistoriaDAO.findByPlaca(txtPlaca.getText()).get(0).getKilometragem());

                        if (vistoriaDAO.findByPlaca(txtPlaca.getText()).get(0).getResultado() != 'a') {
                            jLabelMotivo.setText("Retorno");
                            jLabelMotivo.setForeground(Color.red);

                        }

                    }

                    // Passa o foco para o campo cpf
                    txtCpf.requestFocusInWindow();

                } else {

                    int op = JOptionPane.showConfirmDialog(null, "Veiculo não encontrado, deseja cadastrar?");

                    if (op == 0) {
                        VeiculoVisao frame = new VeiculoVisao(txtPlaca.getText());

                        frame.setModal(true);
                        frame.setVisible(true);

                        jButton1.doClick();
                    } else {
                        TxtModeloVeiculo.setText("");
                        txtPlaca.requestFocus();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor inserir 7 digitos");
                txtPlaca.requestFocus();
            }
        } else {

            JOptionPane.showMessageDialog(null, "Favor digitar a placa");
            txtPlaca.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        // Restringe caracteres no campo
        String caracteres = "0987654321ABCDEFGHIJKLMNOPQRSTUVXZKWYabcdefghijklmnopqrstuvxzkwy";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void txtPlacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusGained
        // Quando focado seleciona todo o conteudo
        JTextField txt = (JTextField) evt.getComponent();
        txt.selectAll();
    }//GEN-LAST:event_txtPlacaFocusGained

    private void jButtonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagoActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            int op = JOptionPane.showConfirmDialog(null, "Deseja mudar a situação da vistoria?");

            if (op == 0) {
                Vistoria v = vistorias.get(linha);

                if (v.getPagamento() == null) {
                    PagamentoVistoria frame = new PagamentoVistoria(v);
                    frame.setModal(true);
                    frame.setVisible(true);

                } else {
                    int op2 = JOptionPane.showConfirmDialog(null, "Existe um pagamento registrado, deseja removê-lo?");

                    if (op2 == 0) {
                        v.setPagamento(null);
                        vistoriaDAO.merge(v);
                        JOptionPane.showMessageDialog(null, "Pagamento removido!");
                    }
                }
                atualizaTabela(vistoriaDAO.findAll());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro da tabela!");
        }
        
    }//GEN-LAST:event_jButtonPagoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            int op = JOptionPane.showConfirmDialog(null, "Deseja editar os dados da vistoria?");

            if (op == 0) {
                Vistoria v = vistorias.get(linha);

                jTextFieldID.setText(v.getId() + "");

                // Bloqueia campos
                txtCpf.setEnabled(false);
                jButton1.setEnabled(false);
                txtCpf.setEnabled(false);
                jButton4.setEnabled(false);
                txtPlaca.setEnabled(false);

                // Dados do veiculo
                txtPlaca.setText(v.getVeiculo().getPlaca());
                TxtModeloVeiculo.setText(v.getVeiculo().getModelo());
                TxtMarcaVeiculo.setText(v.getVeiculo().getMarca());
                TxtCorVeiculo.setText(v.getVeiculo().getCor());
                jTextFieldKilometragem.setText(v.getKilometragem() + "");

                //Dados do cliente
                txtCpf.setText(v.getCliente().getCpf());
                TxtNomeCliente.setText(v.getCliente().getNome());
                TxtTelefoneCliente.setText(v.getCliente().getTelefone());

                //Dados da Vistoria
                if (v.getParceiro() != null) {
                    jComboBoxParceiro.setSelectedItem(v.getParceiro().getNome());
                }

                if (v.getResultado() == 'a') {
                    jRadioButtonAprovado.setSelected(true);
                } else {
                    jRadioButtonReprovado.setSelected(true);
                }

                jLabelMotivo.setText(v.getMotivo());

                editarVistoria.setDatahora(v.getDatahora());

                jLabel6.setText("Editar Vistoria");

                PainelComAbas.setSelectedIndex(1);
                PainelComAbas.setEnabledAt(0, false);
                PainelComAbas.setEnabledAt(1, true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro da tabela!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        limparCampos();
        jLabel6.setText("Nova Vistoria");
        PainelComAbas.setSelectedIndex(1);
        PainelComAbas.setEnabledAt(0, false);
        PainelComAbas.setEnabledAt(1, true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBoxOpPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpPesquisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            int op = JOptionPane.showConfirmDialog(null, "Confirma a exclusão?");

            if (op == 0) {
                Vistoria v = vistorias.get(linha);
                vistoriaDAO.remove(v);
                JOptionPane.showMessageDialog(null, "Registro excluído.", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
                atualizaTabela(vistoriaDAO.findAll());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro da tabela!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jRadioButtonPlaca.isSelected() == true) {
            if (!jTextFieldCampoPesquisa.getText().equals("")) {
                String pesquisa = jTextFieldCampoPesquisa.getText();
                switch (jComboBoxOpPesquisa.getSelectedIndex()) {
                    case 0: {
                        List<Vistoria> lista = vistoriaDAO.findByPlaca(pesquisa);
                        if (lista == null
                                || lista.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            atualizaTabela(lista);
                        }
                        break;
                    }
                    case 1: {
                        List<Vistoria> lista = vistoriaDAO.findByNome(pesquisa);
                        if (lista == null
                                || lista.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            atualizaTabela(lista);
                        }
                        break;
                    }
                    default:
                        List<Vistoria> lista = vistoriaDAO.findByParceiro(pesquisa);
                        if (lista == null
                                || lista.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            atualizaTabela(lista);
                        }
                        break;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor inserir dados para pesquisa.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                atualizaTabela(vistoriaDAO.findAllOrder());
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldCampoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoPesquisaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        PainelComAbas.setEnabledAt(0, true);
        PainelComAbas.setEnabledAt(1, false);
        PainelComAbas.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jRadioButtonAprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAprovadoActionPerformed
        jRadioButtonReprovado.setSelected(false);
    }//GEN-LAST:event_jRadioButtonAprovadoActionPerformed

    private void jRadioButtonReprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReprovadoActionPerformed
        jRadioButtonAprovado.setSelected(false);
    }//GEN-LAST:event_jRadioButtonReprovadoActionPerformed

    private void jTextFieldKilometragemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKilometragemKeyTyped
        // Restringe caracteres no campo
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldKilometragemKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        VistoriaVisao frame = new VistoriaVisao(caixaAberto);
        frame.setModal(true);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButtonAdicionarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPDFActionPerformed
        JFileChooser fc = new JFileChooser(System
                .getProperty("user.dir"));
        fc.setMultiSelectionEnabled(false);
        javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) {
                return f.isDirectory()
                        || f.getName().toLowerCase().endsWith(
                                ".txt");
            }

            public String getDescription() {
                return "(*.txt)";
                // return "(*.xls)";
            }
        };
        fc.addChoosableFileFilter(filter);
        int returnVal = fc.showDialog(null,
                "Open");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txtPDF.setText(fc.getSelectedFile().getAbsolutePath());

        } else if (returnVal == JFileChooser.CANCEL_OPTION) {
            return;

        } else if (returnVal == JFileChooser.UNDEFINED_CONDITION) {
            return;
        }

    }//GEN-LAST:event_jButtonAdicionarPDFActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            int op = JOptionPane.showConfirmDialog(null, "Deseja ver o PDF do Laudo?");

            if (op == 0) {
                Vistoria v = vistorias.get(linha);

                if (v.getLocalpdf() != null) {
                    File filePdf = new File(v.getLocalpdf());
                    try {
                        Desktop.getDesktop().open(filePdf);
                    } catch (IOException ex) {
                        Logger.getLogger(VistoriaVisao.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Não existe nenhum PDF vinculado!");
                }
                vistoriaDAO.merge(v);
                atualizaTabela(vistoriaDAO.findAll());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro da tabela!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButtonPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlacaActionPerformed

        jComboBoxOpPesquisa.setEnabled(true);

    }//GEN-LAST:event_jRadioButtonPlacaActionPerformed

    private String verificaNullParceiro(Parceiro parceiro) {
        if (parceiro == null) {
            return "Nenhum";
        } else {
            return parceiro.getNome();
        }
    }

    private void limparCampos() {
        jLabel6.setText("Nova Vistoria");
        jTextFieldID.setText("");
        txtPlaca.setText("");
        TxtModeloVeiculo.setText("");
        TxtMarcaVeiculo.setText("");
        TxtCorVeiculo.setText("");
        txtCpf.setText("");
        jComboBoxParceiro.setSelectedIndex(0);
        jTextFieldUltimaVistoria.setText("");
        jTextFieldUltimaKm.setText("");
        TxtNomeCliente.setText("");
        TxtTelefoneCliente.setText("");
        jTextFieldKilometragem.setText("");
        jLabelMotivo.setText("Transferência");
        jLabelMotivo.setForeground(Color.black);

    }

    private void atualizaTabela(List<Vistoria> lista) {
        DefaultTableModel dtm = (DefaultTableModel) tabela.getModel();
        dtm.setNumRows(0); // excluir os registros que estão na JTable
        vistorias = lista;
        DateFormat dateDia = new SimpleDateFormat("dd/MM/yyyy");
        DateFormat dateHora = new SimpleDateFormat("HH:mm:ss");
        if (vistorias != null) {
            for (Vistoria v : vistorias) {
                dtm.addRow(new Object[]{v.getVeiculo().getPlaca(), v.getVeiculo().getModelo(), v.getMotivo(), dateDia.format(v.getDatahora()), dateHora.format(v.getDatahora()), verificaSituacao(v.getPagamento()), verificaPagamento(v.getPagamento()), verificaNullParceiro(v.getParceiro()), retornaResultado(v.getResultado())});
            }
        }

    }

    private String verificaSituacao(Pagamento situacao) {
        if (situacao == null) {
            return "Não pago";
        } else {
            return "Pago";
        }
    }

    private String verificaPagamento(Pagamento pag) {
        NumberFormat nf = NumberFormat.getCurrencyInstance();
        if (pag == null) {
            return "-";
        } else {
            return nf.format(pag.getValorcobrado());
        }
    }

    private void atualizaParceiros(List<Parceiro> parceiros) {
        String str = null;

        for (int i = 0; i < parceiros.size(); i++) {

            str = (String) parceiros.get(i).getNome();
            jComboBoxParceiro.addItem(str);
        }
    }

    private String getDateTime() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistoriaVisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistoriaVisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistoriaVisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistoriaVisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistoriaVisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PainelComAbas;
    private javax.swing.JTextField TxtCorVeiculo;
    private javax.swing.JTextField TxtMarcaVeiculo;
    private javax.swing.JTextField TxtModeloVeiculo;
    private javax.swing.JTextField TxtNomeCliente;
    private javax.swing.JTextField TxtTelefoneCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdicionarPDF;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPago;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxOpPesquisa;
    private javax.swing.JComboBox<String> jComboBoxParceiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButtonAprovado;
    private javax.swing.JRadioButton jRadioButtonPlaca;
    private javax.swing.JRadioButton jRadioButtonReprovado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaLaudo;
    private javax.swing.JTextField jTextFieldCampoPesquisa;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldKilometragem;
    private javax.swing.JTextField jTextFieldUltimaKm;
    private javax.swing.JTextField jTextFieldUltimaVistoria;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtPDF;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    private Object retornaResultado(char resultado) {
        if (resultado == 'a') {
            return "Aprovado";
        } else {
            return "Reprovado";
        }
    }
}
